version: "3.3"
services:
      
  api:
    image: liinhhnt/web-api
    container_name: api
    restart: unless-stopped
    networks:
      - client-api
      - admin-api
    ports:
      - 8000:8000

  client:
    depends_on:
      - "api"
    image: liinhhnt/web-client
    container_name: client
    restart: unless-stopped
    networks:
      - client-api
    ports:
      - 3123:3000

  admin:
    depends_on:
      - "api"
    image: liinhhnt/web-admin
    restart: unless-stopped
    container_name: admin
    networks:
      - admin-api
    ports:
      - 3124:3000
networks:
  client-api:
  admin-api: