name: Build, Push, Ssh, Pull, Down, Up

on:
  push:
    branches:
      - 'main'

jobs:
  build-and-push:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push API Image
        uses: docker/build-push-action@v2
        with:
          context: ./api
          push: true
          tags: liinhhnt/web-api

      - name: Build and push Admin Image
        uses: docker/build-push-action@v2
        with:
          context: ./admin
          push: true
          tags: liinhhnt/web-admin

      - name: Build and push Client Image
        uses: docker/build-push-action@v2
        with:
          context: ./client
          push: true
          tags: liinhhnt/web-client

  pull-and-up:
    name: Pull new image and deploy to Google Cloud
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout files
        uses: actions/checkout@v3
      
      - name: Create SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ../private.key
          sudo chmod 600 ../private.key
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}
          SSH_KEY_PATH: ${{ github.workspace }}/../private.key


      - name: SSH to GGC
        run:
          ssh -i $SSH_KEY_PATH linhnt.ict@34.143.146.31 "docker compose pull && docker compose down && docker compose up -d"

      # - name: Pull latest images
      #   run: docker-compose pull

      # - name: Down old images
      #   run: docker-compose down

      # - name: Deploy with Docker Compose
      #   run: docker-compose up -d